### ISSUE TITLE
Add more dev tools 

### ISSUE THREAD

**Issue by inidaname** [thisdot/tech-dev-tooling#15]
We have a few tools on the list but we could always use some more.
Please read through the [contributing documentation](https://github.com/thisdot/tech-dev-tooling/blob/main/CONTRIBUTING.md) before making a pull request.

Please note: This issue will remain open and not be assigned to anyone because we encourage multiple people to work on this.

**Comment by clairecharles** [comment]
hey @inidaname I would love to work on this :)

**Comment by cyborglaksh** [comment]
I have added a couple of tools I use in my development cycle. 
Please spare some time & check them out & see if we can merge it.
