### ISSUE TITLE
Alphabetize lists and remove duplicates 

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/tech-dev-tooling#39]
Some of the lists are out of order and need to be alphabetized again.
Please go through each of the categories, and sort them in alphabetical order.
If there are duplicates, please remove them after the list has been put in order. 

If you are interested in working on this issue, please comment below and it will be assigned to you.
If you are new to this repository, please read through the [contributing docs](https://github.com/thisdot/tech-dev-tooling/blob/main/CONTRIBUTING.md) first.

**Please note**: this issue will be assigned on a first come basis. Please do not start work on this issue until it has been assigned to you.

**Comment by DakshVarshney1409** [comment]
I want to contribute @jdwilkin4. Please assign it to me.

**Comment by jdwilkin4** [comment]
@DakshVarshney1409 The issue has been assigned to you
